### ISSUE TITLE
Can't trigger my Cyclops 

### ISSUE THREAD

**Issue by Guennideluxe** [jonnew/cyclops#19]
Hi Jon,

I'm Mathias from RWTH Aachen, Germany. We just bought 2 of the new  (already assembled) Cyclops 3.6 with tennsy 3.2 installed.
I worked in the past already with the old Cyclops with an arduino Leonardo and was quite happy with it. 
But now I have a problem with the trigger. 
I installed the recent version of the arduino IDE 1.8.5, installed the add on to program the teensy and the recent Cyclops library. 
I loaded the trigger_pulse example to the teensy without a problem and set the feedback loop to current. I tried to trigger the Cyclops over the trig bnc port with a 5v spuare puls but nothing happens. I maked sure that the LED worked fine. I tried another example like chirp and it worked flawless. I have this problem on both Cyclops so i guess it's not a hardware problem. 
I read already all documentation i could  find but didn't found a solution. 
I hope you can help me out with this. 
I'm looking forward to here from you. 

Greetings from Germany

Mathias

**Comment by jonnew** [comment]
Hi Mathias

This should now be fixed. It was simply a matter of the example script not being updated to match the new library (e.g. required called to static `Cyclops::begin()` and the addition of a direction argument (`RISING`, `FALLING`, `CHANGED`) to the `set_trigger` method.
