### ISSUE TITLE
EMI shielding

### ISSUE THREAD

**Issue by jsiegle** [jonnew/cyclops#4]
The manual recommends the use of conductive coating for EMI suppression. Is this really necessary?

**Comment by jonnew** [comment]
Probably not in most situations. This is especially true if you are using a digital acquisition system, e.g. with Intan headstages and the cyclops is very far away from the analog portion of the circuit.

**Comment by jsiegle** [comment]
I am, as it turns out

**Comment by jonnew** [comment]
@jsiegle, sorry, I deleted your last comment when I clicked on it, can you repost?

**Comment by jsiegle** [comment]
Just wanted to add that the power connector for the Arduino touches the bottom of the enclosure, so anyone using a conductive coating should be careful not to spray it there.

**Comment by jonnew** [comment]
Ah, yes. I need to add this to the manual. When installing the arduino, I always remove the power jack using a hot air gun to prevent this.

**Comment by jonnew** [comment]
Also to note: keeping cables short and low inductance is the best way to reduce EMI and improve the device's performance. I actually mount my LED right to the back of the device using a copper clad PC board with a couple banana plugs screwed into it.

![out](https://cloud.githubusercontent.com/assets/1429475/14194848/bed2295e-f780-11e5-993f-c7fbb091a3e7.png)
![out1](https://cloud.githubusercontent.com/assets/1429475/14194852/c52b00c8-f780-11e5-9320-535ed0498226.png)
